# Generated by Django 3.2.7 on 2023-08-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220518_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='epoch_time_micro',
            field=models.BigIntegerField(default=1693103615759365),
        ),
        migrations.AlterField(
            model_name='order',
            name='epoch_time_micro',
            field=models.BigIntegerField(default=1693103615760364),
        ),
        migrations.AlterField(
            model_name='stockhiddenattribute',
            name='epoch_time_micro',
            field=models.BigIntegerField(default=1693103615759365),
        ),
    ]
